In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import sys
sys.path.append("../scripts")

from data_loader import load_data

In [3]:
orders, order_items, products, refunds = load_data("../../data/raw")

In [4]:
# import pandas as pd

# orders = pd.read_csv(r"../../data/raw/orders.csv")
# order_items = pd.read_csv(r"../../data/raw/order_items.csv")
# products = pd.read_csv(r"../../data/raw/products.csv")
# refunds = pd.read_csv(r"../../data/raw/order_item_refunds.csv")

In [5]:
print("Orders Shape:", orders.shape)
print("Order Items Shape:", order_items.shape)
print("Products Shape:", products.shape)
print("Refunds Shape:", refunds.shape)

Orders Shape: (32313, 8)
Order Items Shape: (40025, 7)
Products Shape: (4, 3)
Refunds Shape: (1731, 5)

In [6]:
print("ORDERS")
print("\nFirst 5 Rows:")
display(orders.head())

print("\nColumns:")
print(orders.columns.tolist())

print("\nData Types:")
display(orders.dtypes)

print("\nInformation:")
orders.info()

print("\nStatistical Summary:")
display(orders.describe())

ORDERS

First 5 Rows:

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49

Columns:
['order_id', 'created_at', 'website_session_id', 'user_id', 'primary_product_id', 'items_purchased', 'price_usd', 'cogs_usd']

Data Types:

order_id                int64
created_at             object
website_session_id      int64
user_id                 int64
primary_product_id      int64
items_purchased         int64
price_usd             float64
cogs_usd              float64
dtype: object

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ MB

Statistical Summary:

,order_id,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
count,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000,32313.000000
mean,16157.000000,258292.288707,215691.622629,1.392474,1.238666,59.991636,22.355406
std,9328.103961,132427.649842,108402.203189,0.732277,0.426274,17.808771,6.238621
min,1.000000,20.000000,13.000000,1.000000,1.000000,29.990000,9.490000
25%,8079.000000,144828.000000,124135.000000,1.000000,1.000000,49.990000,19.490000
50%,16157.000000,263554.000000,221461.000000,1.000000,1.000000,49.990000,19.490000
75%,24235.000000,374799.000000,310542.000000,2.000000,1.000000,59.990000,22.490000
max,32313.000000,472818.000000,394273.000000,4.000000,2.000000,109.980000,41.980000

In [7]:
print("PRODUCTS")

print("\nFirst 5 Rows:")
display(products.head())

print("\nColumns:")
print(products.columns.tolist())

print("\nData Types:")
display(products.dtypes)

print("\nInformation:")
products.info()

print("\nStatistical Summary:")
display(products.describe(include="all"))

PRODUCTS

First 5 Rows:

   product_id           created_at                product_name
0           1  2012-03-19 08:00:00      The Original Mr. Fuzzy
1           2  2013-01-06 13:00:00       The Forever Love Bear
2           3  2013-12-12 09:00:00    The Birthday Sugar Panda
3           4  2014-02-05 10:00:00  The Hudson River Mini bear

Columns:
['product_id', 'created_at', 'product_name']

Data Types:

product_id       int64
created_at      object
product_name    object
dtype: object

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4 non-null      int64
 1   created_at    4 non-null      object
 2   product_name  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

Statistical Summary:

        product_id           created_at            product_name
count     4.000000                    4                       4
unique         NaN                    4                       4
top            NaN  2012-03-19 08:00:00  The Original Mr. Fuzzy
freq           NaN                    1                       1
mean      2.500000                  NaN                     NaN
std       1.290994                  NaN                     NaN
min       1.000000                  NaN                     NaN
25%       1.750000                  NaN                     NaN
50%       2.500000                  NaN                     NaN
75%       3.250000                  NaN                     NaN
max       4.000000                  NaN                     NaN

In [8]:
print("ORDER ITEMS")


print("\nFirst 5 Rows:")
display(order_items.head())

print("\nColumns:")
print(order_items.columns.tolist())

print("\nData Types:")
display(order_items.dtypes)

print("\nInformation:")
order_items.info()

print("\nStatistical Summary:")
display(order_items.describe())

ORDER ITEMS

First 5 Rows:

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49

Columns:
['order_item_id', 'created_at', 'order_id', 'product_id', 'is_primary_item', 'price_usd', 'cogs_usd']

Data Types:

order_item_id        int64
created_at          object
order_id             int64
product_id           int64
is_primary_item      int64
price_usd          float64
cogs_usd           float64
dtype: object

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  object
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: float64(2), int64(4), object(1)
memory usage: 2.1+ MB

Statistical Summary:

,order_item_id,order_id,product_id,is_primary_item,price_usd,cogs_usd
count,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000,40025.000000
mean,20013.000000,17121.957502,1.770019,0.807320,48.432473,18.047976
std,11554.366599,9053.765867,1.085561,0.394408,8.012370,3.856821
min,1.000000,1.000000,1.000000,0.000000,29.990000,9.490000
25%,10007.000000,9871.000000,1.000000,1.000000,49.990000,19.490000
50%,20013.000000,17490.000000,1.000000,1.000000,49.990000,19.490000
75%,30019.000000,24818.000000,2.000000,1.000000,49.990000,19.490000
max,40025.000000,32313.000000,4.000000,1.000000,59.990000,22.490000

In [9]:
print("REFUNDS")
print("\nFirst 5 Rows:")
display(refunds.head())

print("\nColumns:")
print(refunds.columns.tolist())

print("\nData Types:")
display(refunds.dtypes)

print("\nInformation:")
refunds.info()

print("\nStatistical Summary:")
display(refunds.describe())

REFUNDS

First 5 Rows:

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99

Columns:
['order_item_refund_id', 'created_at', 'order_item_id', 'order_id', 'refund_amount_usd']

Data Types:

order_item_refund_id      int64
created_at               object
order_item_id             int64
order_id                  int64
refund_amount_usd       float64
dtype: object

Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   object
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: float64(1), int64(3), object(1)
memory usage: 67.7+ KB

Statistical Summary:

       order_item_refund_id  order_item_id      order_id  refund_amount_usd
count           1731.000000    1731.000000   1731.000000        1731.000000
mean             866.000000   18472.214905  15868.242057          49.300225
std              499.840975   11438.074606   9096.061945           4.956015
min                1.000000      57.000000     57.000000          29.990000
25%              433.500000    7417.000000   7412.000000          49.990000
50%              866.000000   19858.000000  17375.000000          49.990000
75%             1298.500000   26900.000000  22539.500000          49.990000
max             1731.000000   39950.000000  32255.000000          59.990000

In [10]:
print("Missing Values - Orders")
display(orders.isnull().sum())

print("\nMissing Values - Order Items")
display(order_items.isnull().sum())

print("\nMissing Values - Products")
display(products.isnull().sum())

print("\nMissing Values - Refunds")
display(refunds.isnull().sum())

Missing Values - Orders

order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64

Missing Values - Order Items

order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64

Missing Values - Products

product_id      0
created_at      0
product_name    0
dtype: int64

Missing Values - Refunds

order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64

In [11]:
def missing_percentage(df):
    result = pd.DataFrame({
        "missing_count": df.isnull().sum(),
        "missing_percentage": df.isnull().mean() * 100
    })
    
    return result.sort_values(
        "missing_percentage",
        ascending=False
    )

In [12]:
display(missing_percentage(orders))
display(missing_percentage(order_items))
display(missing_percentage(products))
display(missing_percentage(refunds))

                    missing_count  missing_percentage
order_id                        0                 0.0
created_at                      0                 0.0
website_session_id              0                 0.0
user_id                         0                 0.0
primary_product_id              0                 0.0
items_purchased                 0                 0.0
price_usd                       0                 0.0
cogs_usd                        0                 0.0

                 missing_count  missing_percentage
order_item_id                0                 0.0
created_at                   0                 0.0
order_id                     0                 0.0
product_id                   0                 0.0
is_primary_item              0                 0.0
price_usd                    0                 0.0
cogs_usd                     0                 0.0

              missing_count  missing_percentage
product_id                0                 0.0
created_at                0                 0.0
product_name              0                 0.0

                      missing_count  missing_percentage
order_item_refund_id              0                 0.0
created_at                        0                 0.0
order_item_id                     0                 0.0
order_id                          0                 0.0
refund_amount_usd                 0                 0.0

In [13]:
print("Orders duplicates:", orders.duplicated().sum())
print("Order Items duplicates:", order_items.duplicated().sum())
print("Products duplicates:", products.duplicated().sum())
print("Refunds duplicates:", refunds.duplicated().sum())

Orders duplicates: 0
Order Items duplicates: 0
Products duplicates: 0
Refunds duplicates: 0

In [14]:
print(
    "Duplicate order_id:",
    orders["order_id"].duplicated().sum()
)

print(
    "Duplicate order_item_id:",
    order_items["order_item_id"].duplicated().sum()
)

print(
    "Duplicate product_id:",
    products["product_id"].duplicated().sum()
)

print(
    "Duplicate refund_id:",
    refunds["order_item_refund_id"].duplicated().sum()
)

Duplicate order_id: 0
Duplicate order_item_id: 0
Duplicate product_id: 0
Duplicate refund_id: 0

In [15]:
orders["created_at"] = pd.to_datetime(
    orders["created_at"]
)

order_items["created_at"] = pd.to_datetime(
    order_items["created_at"]
)

products["created_at"] = pd.to_datetime(
    products["created_at"]
)

refunds["created_at"] = pd.to_datetime(
    refunds["created_at"]
)

In [16]:
print(orders["created_at"].dtype)
print(order_items["created_at"].dtype)
print(products["created_at"].dtype)
print(refunds["created_at"].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]

In [17]:
print("Negative prices:")
display(orders[orders["price_usd"] < 0])

print("Negative COGS:")
display(orders[orders["cogs_usd"] < 0])

print("Invalid items purchased:")
display(orders[orders["items_purchased"] <= 0])

Negative prices:

Empty DataFrame
Columns: [order_id, created_at, website_session_id, user_id, primary_product_id, items_purchased, price_usd, cogs_usd]
Index: []

Negative COGS:

Empty DataFrame
Columns: [order_id, created_at, website_session_id, user_id, primary_product_id, items_purchased, price_usd, cogs_usd]
Index: []

Invalid items purchased:

Empty DataFrame
Columns: [order_id, created_at, website_session_id, user_id, primary_product_id, items_purchased, price_usd, cogs_usd]
Index: []

In [18]:
print("Negative item prices:")
display(order_items[order_items["price_usd"] < 0])

print("Negative item COGS:")
display(order_items[order_items["cogs_usd"] < 0])

Negative item prices:

Empty DataFrame
Columns: [order_item_id, created_at, order_id, product_id, is_primary_item, price_usd, cogs_usd]
Index: []

Negative item COGS:

Empty DataFrame
Columns: [order_item_id, created_at, order_id, product_id, is_primary_item, price_usd, cogs_usd]
Index: []

In [19]:
missing_orders = order_items[
    ~order_items["order_id"].isin(
        orders["order_id"]
    )
]

print(
    "Order items without matching order:",
    len(missing_orders)
)

Order items without matching order: 0

In [20]:
missing_products = order_items[
    ~order_items["product_id"].isin(
        products["product_id"]
    )
]

print(
    "Order items without matching product:",
    len(missing_products)
)

Order items without matching product: 0

In [21]:
missing_products = order_items[
    ~order_items["product_id"].isin(
        products["product_id"]
    )
]

print(
    "Order items without matching product:",
    len(missing_products)
)

Order items without matching product: 0

In [22]:
order_summary = (
    order_items
    .groupby("order_id")
    .agg(
        total_items=("order_item_id", "count"),
        revenue=("price_usd", "sum"),
        cogs=("cogs_usd", "sum")
    )
    .reset_index()
)

In [23]:
order_summary["profit"] = (
    order_summary["revenue"]
    - order_summary["cogs"]
)

In [24]:
order_summary["profit_margin"] = np.where(
    order_summary["revenue"] != 0,
    (order_summary["profit"]
     / order_summary["revenue"]) * 100,
    0
)

In [25]:
display(order_summary.head())

   order_id  total_items  revenue   cogs  profit  profit_margin
0         1            1    49.99  19.49    30.5      61.012202
1         2            1    49.99  19.49    30.5      61.012202
2         3            1    49.99  19.49    30.5      61.012202
3         4            1    49.99  19.49    30.5      61.012202
4         5            1    49.99  19.49    30.5      61.012202

In [26]:
orders_analysis = orders.merge(
    order_summary,
    on="order_id",
    how="left"
)

In [27]:
print("Orders Analysis Shape:", orders_analysis.shape)

display(
    orders_analysis.head()
)

Orders Analysis Shape: (32313, 13)

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd,total_items,revenue,cogs,profit,profit_margin
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49,1,49.99,19.49,30.5,61.012202
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49,1,49.99,19.49,30.5,61.012202
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49,1,49.99,19.49,30.5,61.012202
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49,1,49.99,19.49,30.5,61.012202
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49,1,49.99,19.49,30.5,61.012202

In [28]:
orders_analysis["year"] = (
    orders_analysis["created_at"].dt.year
)

orders_analysis["month"] = (
    orders_analysis["created_at"].dt.month
)

orders_analysis["month_name"] = (
    orders_analysis["created_at"].dt.month_name()
)

orders_analysis["day_name"] = (
    orders_analysis["created_at"].dt.day_name()
)

orders_analysis["date"] = (
    orders_analysis["created_at"].dt.date
)

In [29]:
display(
    orders_analysis[
        [
            "order_id",
            "user_id",
            "created_at",
            "total_items",
            "revenue",
            "cogs",
            "profit",
            "profit_margin"
        ]
    ].head()
)

,order_id,user_id,created_at,total_items,revenue,cogs,profit,profit_margin
0,1,20,2012-03-19 10:42:46,1,49.99,19.49,30.5,61.012202
1,2,104,2012-03-19 19:27:37,1,49.99,19.49,30.5,61.012202
2,3,147,2012-03-20 06:44:45,1,49.99,19.49,30.5,61.012202
3,4,160,2012-03-20 09:41:45,1,49.99,19.49,30.5,61.012202
4,5,177,2012-03-20 11:28:15,1,49.99,19.49,30.5,61.012202